development:
  adapter: mysql
  encoding: utf8
  database: openmrs_dev
  user: root

test:
  adapter: mysql
  encoding: utf8
  database: openmrs_test
  user: root

production:
  adapter: mysql
  encoding: utf8
  database: openmrs_prod
  user: root

